# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    
    encoders: 
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 13
        
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    providers:
        fos_userbundle:
           id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^(_(prifiler|wdt)|css|images|js)/
            security: false
            
        main: 
            pattern:   ^/
            anonymous: true
            form_login:
               provider: fos_userbundle
               default_target_path: fos_user_profile_show
            logout: true
            remember_me:
                secret:        '%secret%'
                lifetime: 604800 # 1 week
                path: /
    
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }